version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb_amazon
    ports:
      - 27017:27017
    volumes:
      - amazon:/data/db

  cache:
    image: redis:6.2
    container_name: wallet-redis
    ports:
      - 6379:6379
volumes:
  amazon:
